[tool.poetry]
name = "podcasts"
version = "0.1.0"
description = ""
authors = ["Richlogs <richcostello@outlook.co.nz>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
